name: Regénérer le dépôt F-Droid

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Configurer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Installer F-Droid Server
        run: |
          pip install fdroidserver

     - name: Préparer l'environnement et générer l'index
        run: |
          cd fdroid
          mkdir -p metadata
          # On initialise avec le vrai nom et la vraie URL de ton projet
          fdroid init --no-prompt --repo-name "WinStars3 Astro Repo" --repo-icon --repo-url "https://franckrichard01.github.io/WinStars3-FDroid/"
          fdroid update --create-metadata

      - name: Configurer Pages
        uses: actions/configure-pages@v4

      - name: Téléverser les fichiers du dépôt
        uses: actions/upload-pages-artifact@v3
        with:
          # On publie tout le dossier pour avoir la structure /repo/ en ligne
          path: './fdroid'

      - name: Déployer sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4