name: Regénérer le dépôt F-Droid

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Configurer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Installer F-Droid Server
        run: |
          pip install fdroidserver

      - name: Générer l'index du dépôt
        run: |
          fdroid init --unattended
          fdroid update --create-metadata

      - name: Configurer Pages
        uses: actions/configure-pages@v4

      - name: Téléverser les fichiers du dépôt
        uses: actions/upload-pages-artifact@v3
        with:
          path: './fdroid/repo'

      - name: Déployer sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4