name: Regénérer le dépôt F-Droid

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Force l'utilisation de Node 24 pour nettoyer les avertissements GitHub
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Configurer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Installer F-Droid Server
        run: |
          pip install fdroidserver

      - name: Préparer l'environnement et générer l'index
        run: |
          cd fdroid
          # Crée le dossier des métadonnées s'il manque
          mkdir -p metadata
          # Initialise proprement le dépôt
          fdroid init --no-prompt
          
          # MODIFICATION ICI : On remplace les fausses URL par ta vraie adresse GitHub Pages
          sed -i 's|http://localhost:8000/fdroid/repo|https://franckrichard01.github.io/WinStars3-FDroid|g' config.yml
          sed -i 's|https://MyFirstFDroidRepo.org/fdroid/repo|https://franckrichard01.github.io/WinStars3-FDroid|g' config.yml
          
          # Force la création de l'index mis à jour
          fdroid update --create-metadata

      - name: Configurer Pages
        uses: actions/configure-pages@v4

      - name: Téléverser les fichiers du dépôt
        uses: actions/upload-pages-artifact@v3
        with:
          # On publie le sous-dossier de déploiement qui vient d'être généré par F-Droid
          path: './fdroid/repo'

      - name: Déployer sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4